### ISSUE TITLE
add the link to the MDN page that lists the polyfill

### ISSUE THREAD

**Issue by Pomax** [yola/classlist-polyfill-old#2]
It's probably good idea to add a link to https://developer.mozilla.org/docs/Web/API/Element/classList in the README.md for those who want to know what this "MDN polyfill" is =)

**Comment by kahnvex** [comment]
It is in the source.

https://github.com/yola/classlist-polyfill/blob/master/src/index.js#L14-L16

But I'll add it anyway.

**Comment by kahnvex** [comment]
A pull also would have been appropriate.

**Comment by kahnvex** [comment]
Fixed via: https://github.com/yola/classlist-polyfill/pull/3

**Comment by Pomax** [comment]
remember that not everyone can always file a PR, but everyone can always file an issue. That's what the issue tracker's for.
