### ISSUE TITLE
'self is not defined' in CommonJS context

### ISSUE THREAD

**Issue by vovacodes** [yola/classlist-polyfill-old#4]
`self` is not implicitly defined in the CommonJS context, so it causes error when I try to use this polyfill.

problem lines are:
https://github.com/yola/classlist-polyfill/blob/master/src/index.js#L18
https://github.com/yola/classlist-polyfill/blob/master/src/index.js#L187

**Comment by kahnvex** [comment]
@wizardzloy thanks for the contribution. This has been released in [classlist-polyfill@1.0.2](https://www.npmjs.com/package/classlist-polyfill).
