### ISSUE TITLE
this repo is a duplicate

### ISSUE THREAD

**Issue by notslang** [yola/classlist-polyfill-old#7]
... of https://github.com/eligrey/classList.js

@eligrey wrote it, put it under public domain, and then it was used in the MDN article. It still might be worth forking to fix the weird version scheme, but it shouldn’t be a totally independent repo.

**Comment by kahnvex** [comment]
https://github.com/eligrey/classList.js was never published to npm, which is the main reason we created this repository. Publishing something that you do not have ownership of to a package manager seems weird.

**Comment by notslang** [comment]
I'm not saying that this repo shouldn't exist, it should just be made into a fork of https://github.com/eligrey/classList.js ... or at least reference it rather than the MDN article

**Comment by kahnvex** [comment]
> or at least reference it rather than the MDN article

A pull request would be welcomed.

**Comment by thomasw** [comment]
Fixed by https://github.com/yola/classlist-polyfill/pull/9
